feat: add cognito with Lucas

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -1,4 +1,3 @@
-
 name: CD
 
 on:
@@ -13,52 +12,73 @@ on:
 jobs:
   DeployToAWS:
     environment:
-        name: ${{ github.ref_name }}
+      name: ${{ github.ref_name }}
     runs-on: ubuntu-latest
     permissions:
       id-token: write
       contents: read
 
     steps:
-        - uses: actions/checkout@v2
-        - name: Setup AWS Credentials
-          uses: aws-actions/configure-aws-credentials@v2
-          with:
-            aws-region: ${{ vars.AWS_REGION }}
-            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
-            role-session-name: github-action
+      - uses: actions/checkout@v2
+      - name: Set AWS Account ID
+        run: |
+          if [[ "${{ github.ref_name }}" == "dev" ]]; then
+            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOML }}" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
+            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
+          else
+            echo "Invalid branch name!" && exit 1
+          fi
 
-        - name: Setting stage and stack name
-          run: |
-            echo "STAGE=${{ github.ref_name }}" 
-            echo "STACK_NAME=PortalInternoActionStack${{github.ref_name}}" >> $GITHUB_ENV
+      - name: Setup AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-region: ${{ vars.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
+          role-session-name: github-action
 
-        - uses: actions/checkout@v3
-        - uses: actions/setup-python@v4
-          with:
-            python-version: '3.9'
+      - name: Setting stage and stack name
+        run: |
+          echo "STAGE=${{ github.ref_name }}" 
+          if [[ "${{ github.ref_name }}" == "prod" ]]; then
+            echo "STAGE=prod" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+            echo "STAGE=homolog" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
+            echo "STAGE=dev" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "fix/githubActions" ]]; then
+            echo "STAGE=dev" >> $GITHUB_ENV
+          else
+            echo "Invalid branch name!" && exit 1
+          fi
+          echo "STACK_NAME=PortalInternoActionStack${{env.STAGE}}" >> $GITHUB_ENV
 
-        - name: Installing Dependencies
-          run: |
-            npm install -g aws-cdk
-            cd iac
-            pip install -r requirements.txt
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v4
+        with:
+          python-version: "3.9"
 
-        - name: DeployWithCDK
-          run: |
-            cd iac
-            cdk synth
-            cdk deploy --require-approval never 
+      - name: Installing Dependencies
+        run: |
+          npm install -g aws-cdk
+          cd iac
+          pip install -r requirements.txt
 
-          env:
-              AWS_REGION: ${{ vars.AWS_REGION }}
-              AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
-              STACK_NAME: ${{ env.STACK_NAME }}
-              GITHUB_REF_NAME: ${{ github.ref_name }}
-              MSS_NAME: ${{ github.event.repository.name }}
-              S3_ASSETS_CDN: ${{ vars.S3_ASSETS_CDN }}
-              AUTH_DEV_SYSTEM_USERPOOL_ARN_DEV: ${{ secrets.AUTH_DEV_SYSTEM_USERPOOL_ARN_DEV }}
-              AUTH_DEV_SYSTEM_USERPOOL_ARN_PROD: ${{ secrets.AUTH_DEV_SYSTEM_USERPOOL_ARN_PROD }}
-              REPLY_TO_EMAIL: ${{ vars.REPLY_TO_EMAIL }}
-              FROM_EMAIL: ${{ vars.FROM_EMAIL }}
-              HIDDEN_COPY: ${{ vars.HIDDEN_COPY }}
+      - name: DeployWithCDK
+        run: |
+          cd iac
+          cdk synth
+          cdk deploy --require-approval never
+
+        env:
+          AWS_REGION: ${{ vars.AWS_REGION }}
+          AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
+          STACK_NAME: ${{ env.STACK_NAME }}
+          GITHUB_REF_NAME: ${{ github.ref_name }}
+          MSS_NAME: ${{ github.event.repository.name }}
+          S3_ASSETS_CDN: ${{ vars.S3_ASSETS_CDN }}
+          REPLY_TO_EMAIL: ${{ vars.REPLY_TO_EMAIL }}
+          FROM_EMAIL: ${{ vars.FROM_EMAIL }}
+          HIDDEN_COPY: ${{ vars.HIDDEN_COPY }}
